default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: flora
  password: postgres


development:
  <<: *default
  database: chat_dev


test:
  <<: *default
  database: chat_test


production:
  <<: *default
  database: chat_production
  username: buymed_chat
  password: <%= ENV['BUYMED_CHAT_DATABASE_PASSWORD'] %>
